"""Shared constants used by both Flask routes and FastAPI routes."""

PIPELINE_SCHEMA = [
    {
        "id": "init",
        "label": "准备任务",
        "input": "用户输入的 URL/本地路径和生成参数",
        "output": "规范化 source_type、job_key、subprocess 命令",
        "failure_codes": ["URL_REQUIRED", "LOCAL_PATH_REQUIRED", "UNSUPPORTED_SOURCE", "DUPLICATE_JOB"],
    },
    {
        "id": "download",
        "label": "下载素材",
        "input": "URL 或本地文件路径",
        "output": "可处理的音频/视频/文章内容",
        "failure_codes": ["NETWORK_ERROR", "AUTH_REQUIRED", "SOURCE_PARSE_ERROR"],
    },
    {
        "id": "subtitle",
        "label": "获取字幕",
        "input": "素材内容或字幕文件",
        "output": "英文/双语字幕片段",
        "failure_codes": ["TRANSCRIPT_NOT_FOUND", "LOCAL_FILE_MISSING", "SOURCE_PARSE_ERROR"],
    },
    {
        "id": "whisper_load",
        "label": "加载转写模型",
        "input": "无字幕音视频和 whisper_model",
        "output": "可用的 Groq 或本地 Whisper 转写器",
        "failure_codes": ["MISSING_DEPENDENCY", "MISSING_KEY"],
    },
    {
        "id": "whisper_transcribe",
        "label": "语音转写",
        "input": "音视频文件",
        "output": "带时间戳的英文片段",
        "failure_codes": ["ASR_FAILED", "QUOTA_EXCEEDED", "TIMEOUT"],
    },
    {
        "id": "resegment_translate",
        "label": "断句合并",
        "input": "Whisper 原始碎片",
        "output": "合并后的完整句子",
        "failure_codes": ["MISSING_KEY", "AI_JSON_ERROR", "NETWORK_ERROR", "QUOTA_EXCEEDED"],
    },
    {
        "id": "ipa_annotate",
        "label": "IPA 音标标注",
        "input": "完整句子",
        "output": "标注连读/吞音/重读的 IPA",
        "failure_codes": ["MISSING_KEY", "AI_JSON_ERROR", "NETWORK_ERROR", "QUOTA_EXCEEDED"],
    },
    {
        "id": "analyze",
        "label": "翻译与分析",
        "input": "完整句子",
        "output": "中文翻译、词汇/句式分析、语流标注",
        "failure_codes": ["MISSING_KEY", "AI_JSON_ERROR", "NETWORK_ERROR", "QUOTA_EXCEEDED"],
    },
    {
        "id": "render",
        "label": "生成页面",
        "input": "课程数据和分析结果",
        "output": "output/*.html",
        "failure_codes": ["RENDER_FAILED", "UNKNOWN_ERROR"],
    },
]

ERROR_CATALOG = {
    "URL_REQUIRED": ("缺少输入", "请输入 B站、YouTube、文章链接，或本地音视频路径。"),
    "LOCAL_PATH_REQUIRED": ("缺少本地文件路径", "请输入本地音视频路径，或使用 file:///D:/path/sample.mp4 格式。"),
    "UNSUPPORTED_SOURCE": ("暂不支持该来源", "请改用 B站、YouTube、文章链接或本地音视频文件。"),
    "DUPLICATE_JOB": ("任务正在运行", "等待当前任务完成，或取消后再重新提交。"),
    "LOCAL_FILE_MISSING": ("本地文件不存在", "检查路径是否正确，Windows 路径建议直接复制完整绝对路径。"),
    "MISSING_KEY": ("缺少 API Key", "检查 .env 或环境变量中的 AI_API_KEY / GROQ_API_KEY。"),
    "MISSING_DEPENDENCY": ("缺少依赖", "按 requirements.txt 安装依赖，并确认 ffmpeg 可在命令行访问。"),
    "AUTH_REQUIRED": ("需要登录凭证", "B站/YouTube 可能需要 cookies 文件，请导出 cookies 后重试。"),
    "NETWORK_ERROR": ("网络请求失败", "检查网络、代理、目标网站是否可访问，然后重试。"),
    "QUOTA_EXCEEDED": ("API 配额或限流", "稍后重试，或切换模型/本地转写。"),
    "AI_JSON_ERROR": ("AI 返回格式错误", "重试当前任务；如果多次失败，切换 mock 模式验证主流程。"),
    "TRANSCRIPT_NOT_FOUND": ("没有可用字幕", "提供字幕文件，或允许使用 Whisper 转写。"),
    "ASR_FAILED": ("语音转写失败", "检查音视频文件是否能正常播放，或换用较小 Whisper 模型。"),
    "CONFIG_ERROR": ("配置不匹配", "检查前端选项与命令行参数是否一致。"),
    "SOURCE_PARSE_ERROR": ("来源解析失败", "检查链接是否完整；B站短链可先在浏览器展开后重试。"),
    "TIMEOUT": ("任务超时", "换用 base/medium 模型，或先用较短素材验证。"),
    "USER_CANCELLED": ("任务已取消", "可以调整参数后重新生成。"),
    "RENDER_FAILED": ("页面生成失败", "检查模板和输出目录权限。"),
    "UNKNOWN_ERROR": ("未知错误", "复制错误和日志后排查。"),
}
